### ISSUE TITLE
[bug] Can't send files

### ISSUE THREAD

**Issue by worldzb** [peers/peerjs#1137]
## Error
binarypack.ts:336 Uncaught Error: Type "function Blob() { [native code] }" not yet supported
    at $0cfd7828ad59115f$export$b9ec4b114aa40074.pack (binarypack.ts:336:12)
    at $0cfd7828ad59115f$export$b9ec4b114aa40074.pack_object (binarypack.ts:466:10)
    at $0cfd7828ad59115f$export$b9ec4b114aa40074.pack (binarypack.ts:334:11)
    at $0cfd7828ad59115f$export$2a703dbb0cb35339 (binarypack.ts:31:9)
    at $9fcfddb3ae148f88$export$f0a5a64d5bb37108._send (BinaryPack.ts:82:16)
    at $9fcfddb3ae148f88$export$f0a5a64d5bb37108.send (DataConnection.ts:138:15)
    at sendFile (useP2P.ts:123:10)
    at handleOnChange (SendFile.tsx:20:5)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    
## environment
    "peerjs": "^1.5.0",
   

When I use 1.5.0, there will be error that Blob does not support。But when I use 1.4.7, there is no problem
I guess, the reason should be on Peerjs-JS-BinaryPack.At 2.0.0, I rewritten the problem with TS

**Comment by worldzb** [comment]
I am using the latest version of Chrome,
`Version 116.0.5845.140 (Official Build) (arm64)`
 so there should be no issue with blob support. I compared the source code of 1.0.1 and 2.0.0, and found the cause of the error.

v1.0.1    /lib/binarypack.js
![image](https://github.com/peers/peerjs/assets/24642015/00aff3da-f237-4490-88e5-3da146e952ba)

v2.0.0    /lib/binarypack.ts
![image](https://github.com/peers/peerjs/assets/24642015/ce49b1ed-bc63-4c9e-b9e1-89a9ed47031b)

Based on the comparison of the source code, I suspect that in v2.0.0, there was a missing check for Blob and file types.

**Comment by Lianting-Wang** [comment]
I find it strange that I am still experiencing the same problem when using 1.5.1.
```
<script src="https://unpkg.com/peerjs@1.5.1/dist/peerjs.min.js"></script>
```
```
Uncaught (in promise) Error: Type "function Blob() { [native code] }" not yet supported
    at a.pack (binarypack.ts:336:16)
    at a.pack_object (binarypack.ts:466:10)
    at a.pack (binarypack.ts:334:11)
    at o (binarypack.ts:31:9)
    at eQ._send (BinaryPack.ts:87:16)
    at eQ.send (DataConnection.ts:138:15)
    at sendFile (script.js:114:8)
```

**Comment by ga676005** [comment]
I am having the same problem on 1.5.1. I am simply sending a simple abc.txt with `abc` inside. It would work when I install 1.4.7.
