### ISSUE TITLE
ReferenceError: navigator is not defined when using nestjs

### ISSUE THREAD

**Issue by eassa** [peers/peerjs#1165]
hey, 
i am using nestjs to create a nodejs service as a client to publish streaming from one computer to another connected in the web.
after installing peerjs and initiate it like this 
this.peer = new PeerJs();
it fails with this error 

C:\Repose\webrtc\spring\node_modules\peerjs\dist\lib\supports.ts:8
        readonly isIOS = ["iPad", "iPhone", "iPod"].includes(navigator.platform);
                                                      ^
ReferenceError: navigator is not defined
    at new <anonymous> (C:\Repose\webrtc\spring\node_modules\peerjs\dist\lib\supports.ts:8:55)
    at Object.<anonymous> (C:\Repose\webrtc\spring\node_modules\peerjs\dist\lib\supports.ts:7:25)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Repose\webrtc\spring\src\app.service.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

**Comment by dingavinga1** [comment]
> hey, 
> i am using nestjs to create a nodejs service as a client to publish streaming from one computer to another connected in the web.
> after installing peerjs and initiate it like this 
> this.peer = new PeerJs();
> it fails with this error 
> 
> C:\Repose\webrtc\spring\node_modules\peerjs\dist\lib\supports.ts:8
>         readonly isIOS = ["iPad", "iPhone", "iPod"].includes(navigator.platform);
>                                                       ^
> ReferenceError: navigator is not defined
>     at new <anonymous> (C:\Repose\webrtc\spring\node_modules\peerjs\dist\lib\supports.ts:8:55)
>     at Object.<anonymous> (C:\Repose\webrtc\spring\node_modules\peerjs\dist\lib\supports.ts:7:25)
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
>     at Module.require (node:internal/modules/cjs/loader:1061:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (C:\Repose\webrtc\spring\src\app.service.ts:3:1)
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)

I might be wrong but I think `navigator` is specific to browsers i.e. the frontend, while NestJS is a full-stack framework. Could you provide more information like where in your NestJS server you are trying to access `navigator`?

**Comment by thePeeyush** [comment]
Go to node modules/peerjs/dist/bundler.mjs 

**line 104**

change the code from 104 to 108 with the code given below: 

```
this.isIOS = typeof navigator !== "undefined" ? [
            "iPad",
            "iPhone",
            "iPod"
        ].includes(navigator.platform) : false;
```

**Note** -  this fix works in local build only.
