### ISSUE TITLE
Node : Installing peer throws body-parser error

### ISSUE THREAD

**Issue by kernelfreak** [peers/peerjs#343]
I have a debian server where we are trying to install PeerJS via Node. I am getting an error, which I don't understand. Do I have to download body-parser or something separately.

Error log :
```

npm install peer

npm http GET https://registry.npmjs.org/peer
npm http 304 https://registry.npmjs.org/peer
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/cors
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/body-parser
npm http 304 https://registry.npmjs.org/ws
npm ERR! Error: No compatible version found: body-parser@'^1.9.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.1.0","1.1.1","1.1.2","1.2.0","1.2.1","1.2.2","1.3.0","1.3.1","1.4.0","1.4.1","1.4.2","1.4.3","1.5.0","1.5.1","1.5.2","1.6.0","1.6.1","1.6.2","1.6.3","1.6.4","1.6.5","1.6.6","1.6.7","1.7.0","1.8.0","1.8.1","1.8.2","1.8.3","1.8.4","1.9.0","1.9.1","1.9.2","1.9.3","1.10.0","1.10.1","1.10.2","1.11.0","1.12.0","1.12.1","1.12.2","1.12.3","1.12.4","1.13.0","1.13.1","1.13.2","1.13.3","1.14.0","1.14.1","1.14.2","1.15.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:676:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:591:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR!     at process._makeCallback (node.js:318:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "peer"
npm ERR! cwd /home/deploy/node
npm ERR! node -v v0.9.9
npm ERR! npm -v 1.2.10
npm http 200 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/cors
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/deploy/node/npm-debug.log
npm ERR! not ok code 0
```

Output of npm -v : 1.2.10

Output of node -v : v0.9.9

What am I doing wrong? Thank you.

**Comment by kernelfreak** [comment]
THe issue was solved by installing a newer version of Node and NPM by download the executables and adding them in path.
