### ISSUE TITLE
Getting while installing peerjs using npm

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [peers/peerjs#389]
Hi,
   I'm getting error while installing the **peer.js** like **npm install peerjs --save** and i have attached the npm debug log file.
[npm-debug.txt](https://github.com/peers/peerjs/files/1193677/npm-debug.txt)

**Comment by dukei** [comment]
You should have git installed: https://git-scm.com/download/win

**Comment by Mugesh-Rajaram** [comment]
@dukei Again i'm getting the same error.
[npm-debug.txt](https://github.com/peers/peerjs/files/1197719/npm-debug.txt)

**Comment by dukei** [comment]
> 155 verbose stack Error: not found: git
> 155 verbose stack     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
> 155 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
> 155 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
> 155 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
> 155 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
> 155 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
> 155 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
> 155 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
> 156 verbose cwd D:\Projects\Samples\TextChatApp
> 157 error Windows_NT 6.3.9600
> 158 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "peerjs" "--save"
> 159 error node v6.9.5
> 160 error npm  v3.10.10
> 161 error code ENOGIT
> 162 error not found: git
> 163 error Failed using git.

The problem is still in your git installation.

**Comment by Mugesh-Rajaram** [comment]
@dukei But i didn't found any error in git installation, then why i'm facing the same error is there any other problem do i need to share any other details

**Comment by dukei** [comment]
Have you added git to the system search path?

**Comment by Mugesh-Rajaram** [comment]
@dukei how i have add git in my search path.
