### ISSUE TITLE
PeerJS 1.1.0 not building with browserify (cannot find module utils.js)

### ISSUE THREAD

**Issue by lisajamhoury** [peers/peerjs#585]
I maintain a library that has peerjs as a dependency. I'm trying to update from peerjs version 0.3.14 to the most recent peerjs version 1.1.0 but it will not build with browserify. 

```
Error: Cannot find module '../utils.js' from 'c:\ktron\kinectron\client\node_modules\peerjs\dist'
    at c:\ktron\kinectron\client\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (c:\ktron\kinectron\client\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (c:\ktron\kinectron\client\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at c:\ktron\kinectron\client\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kinectron-api@1.0.0 build: `browserify src/kinectron-client.js -o bin/kinectron.bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kinectron-api@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mhchia** [comment]
+1. Is there any update on this one?

**Comment by el-schneider** [comment]
+1

**Comment by jcollognat** [comment]
I have the same issue, any update on this ?
Thanks

**Comment by rcalfredson** [comment]
I am having this issue too! Tough to figure out, but I know it has something to do with the file `peerjs.min.map`. This contains extra paths that should be `require`-able from `peerjs.min.js`, but for some reason they are not.

In the interim, there is one simple fix that is keeping my app going. I removed `import Peer from 'peerjs';` from my source code, but left the `Peer()` constructors in place. Then, on the pages where the `browserify` script is loaded, I made sure that the `<script>` tag for `peer-js` from the CDN (https://unpkg.com/peerjs@1.3.1/dist/peerjs.min.js) was loaded first. Hope this helps someone.

**Comment by jcollognat** [comment]
Hi,

I gave up the idea of ​​using this library but I'll check your workaround, thanks.

**Comment by FredericBriolet** [comment]
Hi, I also have this issue. Is there any other workaround than putting a `<script>` tag in the html?

**Comment by mhchia** [comment]
@FredericBriolet I turned out to use webpack instead.

**Comment by afrokick** [comment]
Hey guys. Could you please test the latest beta version? It should works. `npm i peerjs@beta`
