### ISSUE TITLE
ability to require peerjs inside the node repl

### ISSUE THREAD

**Issue by natusdrew** [peers/peerjs#677]
I am able to load npm modules inside my node repl. But when I try to load peerjs I receive a window error. This might not be a bug. Maybe just an idea. This way, we can make it easy to try ideas out and play with the code. What do you think? Does peerjs need to rely on the window object to work. If so, should I try using the npm window to do it?

> var pj=require('peerjs');
Uncaught ReferenceError: window is not defined
    at Object.parcelRequire.tI1X../adapter_factory.js (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:38:161)
    at f (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:1:468)
    at p (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:1:544)
    at Object.parcelRequire.sXtV.webrtc-adapter (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:40:161)
    at f (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:1:468)
    at p (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:1:544)
    at Object.parcelRequire.I31f../adapter (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:42:75)
    at f (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:1:468)
    at p (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:1:544)
    at Object.parcelRequire.BHXf.peerjs-js-binarypack (/home/colombia/WebstormProjects/chat-room/node_modules/peerjs/dist/peerjs.min.js:44:285)
>

**Comment by ccrystle** [comment]
bump

**Comment by natesire** [comment]
???

Calendly.com/natesire
Cell: +1.727.359.7503

**Comment by StoneCypher** [comment]
`peerjs` is attempting to reference the browser's `window` global.  `node` does not have one of these.

This means that until the library is taught to not need that, it won't actually work in `node`.
