### ISSUE TITLE
peerjs_min is not a constructor error when initialising Peer

### ISSUE THREAD

**Issue by arnu515** [peers/peerjs#761]
I'm using the [Svelte](https://svelte.dev) framework with [Rollup](https://rollupjs.org) bundler (the default that comes with Svelte). I installed `peerjs` with:
```
npm i peerjs
```

And when I import it, 
```js
import Peer from "peerjs";
const peer = new Peer();
```
I get the error
```
parcelRequire is not defined
```

I found a temporary fix, i.e. to define it manually in `index.html`
```html
<script>
     var parcelRequire;
</script>
```

But now, I'm getting a different error:
```
peerjs_min is not a constructor
```

I am using typescript, so I tried adding `"esModuleInterlop": true` to my `tsconfig.json`, but that did nothing.

Can you please help me? My rollup config is the default that came with Svelte. Many thanks!

**Comment by arnu515** [comment]
So I found a temporary fix, i.e. to use `window.Peer` instead of importing it. This is a really bad fix and I would appreciate it if anyone else would help me :)

**Comment by bosskabouter** [comment]
I was happily using peerjs until a few days ago.. 

In a clean npx create-react-app (18.1.0)
npm i peerjs =>
import Peer from "peerjs";
new Peer(); throws  Uncaught TypeError: peerjs__WEBPACK_IMPORTED_MODULE_4__ is not a constructor

reverting back from current peerjs@1.4.1 to peerjs@1.3.2 resolves the issue.

**Comment by ckqbao** [comment]
I have upgraded peerjs to version 1.4.2 then another issue hits me: 

Uncaught TypeError: Cannot read properties of undefined (reading 'browser')
    at class_1.push../node_modules/peerjs/dist/bundler.mjs.class_1.getBrowser (supports.ts:32:1)
    at new Util (util.ts:51:1)
    at Module../node_modules/peerjs/dist/bundler.mjs (util.ts:182:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)

**Comment by ckqbao** [comment]
> Hey @ckqbao. Oh no. I’ll look into it. Can you tell me how to reproduce this? Maybe open a new issue, so others can find it.

I just use peerjs normally and it works on version 1.3.2. I dont know if any one has the same issue
